@host= localhost
@port=5000
@contentType = application/json


GET http://{{host}}:{{port}}/user
###


# one file
POST http://{{host}}:{{port}}/upload/file
Content-Type: multipart/form-data;boundary=upload_file

--upload_file
Content-Disposition: form-data; name="file"; filename="c9a95517fd512255918d5beaf66e7b0.png"

< C:\Users\4dogs\Desktop\c9a95517fd512255918d5beaf66e7b0.png
--upload_file--

###

# may files
POST http://{{host}}:{{port}}/upload/files
Content-Type: multipart/form-data;boundary=upload_files

--upload_files
Content-Disposition: form-data; name="file1"; filename="c9a95517fd512255918d5beaf66e7b0.png"

< C:\Users\4dogs\Desktop\c9a95517fd512255918d5beaf66e7b0.png
--upload_files
Content-Disposition: form-data; name="file2"; filename="ddff76b400834f6d9669db19218d0c3d_tplv-k3u1fbpfcp-zoom-1 (1).png"

< C:\Users\4dogs\Desktop\ddff76b400834f6d9669db19218d0c3d_tplv-k3u1fbpfcp-zoom-1 (1).png
--upload_files--

### folder
POST http://{{host}}:{{port}}/upload/folder
Content-Type: multipart/form-data;boundary=upload_folder
--folder
Content-Disposition: form-data; name="file";filename="file";

< C:\Users\4dogs\Desktop\public
--folder--